blog/urls.py
#!/usr/local/python3/bin/python3
from django.conf.urls import url
from blog import views
from .feeds import PostRssFeed


urlpatterns = [
    url(r'index/', views.index, name='index'),
    url(r'detail/', views.detail, name='detail'),
    url(r'p_time/(?P<year>[0-9]{4})/(?P<month>[1-9]|1[0-2])/(?P<day>[0-9]|1[0-9]|2[0-9]|3[0-1])/$', views.p_time, name='p_time'),
    url(r'p_category/', views.p_category, name='p_category'),
    url(r'p_tags/', views.p_tags, name='p_tags'),
    url(r'rss/', PostRssFeed(), name='rss'),
    url(r'search/', views.search, name='search'),
    url(r'relation/', views.relation, name='relation'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    # url(r'^rss/', include('rss.urls', namespace='rss'))
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^user/', include('django.contrib.auth.urls'))
]

user/urls.py
from django.conf.urls import url, static
# from django.conf import settings
# from myblog import settings

from user import views

urlpatterns = [
    url(r'register/$', views.register, name='register'),
    url(r'personInfo/$', views.personInfo, name='personInfo'),
]

blog/models.py
from django.db import models
from django.utils.html import strip_tags
from django.urls import reverse
from user.models import User


import markdown

# Create your models here.
class Post(models.Model):
    # title,content,excerpt,created_time,modified_time,tag,category,author,comment
    title = models.CharField(max_length=40, verbose_name='文章标题')
    excerpt = models.CharField(max_length=200, verbose_name="文章摘要", blank=True, null=True)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    modified_time = models.DateTimeField(auto_now= True, verbose_name="修改时间")
    views = models.IntegerField(verbose_name="阅读次数", default=0)
    user = models.ForeignKey(User)

    tag = models.ForeignKey('Tag')
    category = models.ManyToManyField('Category')

    class Meta:
        ordering = ['-create_time']


    def __str__(self):
        return self.title

    def view_times(self):
        self.views += 1
        self.save(update_fields=['views'])


    # 重写save方法
    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions = [
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])

            self.excerpt = strip_tags(md.convert(self.content))[:54]

        super(Post,self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('blog:rss')



class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name='标签')

    def __str__(self):
        return self.name

    pass


class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name="类别")

    def __str__(self):
        return self.name
    pass

comment/models.py
from django.db import models
from blog.models import Post

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=30, verbose_name="姓名")
    email = models.EmailField(max_length=255, verbose_name="邮箱")
    url = models.URLField(max_length=100, verbose_name="网址")
    text = models.TextField(verbose_name="评论")

    create_time = models.DateTimeField(auto_now=True, verbose_name="发表时间")
    post = models.ForeignKey(Post, verbose_name="评论文章")

    def __str__(self):
        self.name

blog/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.views.generic import ListView, DeleteView
from django.core.paginator import Paginator
from math import  ceil
from django.db.models import Q
from django.urls import reverse


import markdown
# 导入锚点模块
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension


from comment.forms import CommentForm
from comment.models import Comment


from .models import Tag

# Create your views here.
def index(request):
    PAGE_NUM = 1
    post_list = Post.objects.all().order_by('-modified_time')

    # 处理标签过来的跳转
    p_tag= request.GET.get('p_tag')
    if p_tag:
        post_list = Post.objects.filter(tag__name=p_tag).order_by("-create_time")

    # 处理分类过来的跳转
    p_category = request.GET.get('p_category')
    if p_category:
        post_list = Post.objects.filter(category__name = p_category).order_by("-create_time")

    page_count = ceil(len(post_list) / PAGE_NUM)
    page = request.GET.get('page', 1)
    # pages = ceil(Post.objects.count())
    paginator = Paginator(post_list, PAGE_NUM)
    post_list = paginator.page(page)

    # 添加搜索的分页逻辑
    search = None

    return render(request, 'blog/index.html', context={'post_list':post_list, "paginator":paginator,"page_num":range(page_count)})


# 使用view视图改写
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = "post_list"

    def get_queryset(self):
        return super(IndexView, self).get_queryset().order_by('-create_time')



def detail(request):
    post_id = request.GET.get('post', 1)
    post = Post.objects.get(id = post_id)
    comment_form = CommentForm()
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        TocExtension(slugify=slugify)
    ])
    post.content = md.convert(post.content)
    post.toc = md.toc
    post.save()
    post.view_times()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            comment_list = Comment.objects.filter(post=post)
            return render(request, 'blog/page.html',
                          context={'post': post, 'comment_list': comment_list, 'comment_form': comment_form})
    else:
        comment_list = Comment.objects.filter(post=post)
        return render(request, 'blog/page.html', context = {'post': post,'comment_list':comment_list,'comment_form':comment_form})



def p_time(request,year,month,day):
    # year = request.GET.get('year')
    # month = request.GET.get('month')

    # post_list =  Post.objects.filter(create_time__year=year,
    #                                  create_time__month=month)
    post_list = Post.objects.filter(modified_time__year=year,
                                    modified_time__month=month,
                                    modified_time__day=day
                                    ).order_by("-create_time")
    # post_list = Post.objects.all()
    return render(request, 'blog/index.html',locals())

def p_category(request):
    p_category = request.GET.get('p_category')

    # post_list = Post.objects.filter(category__name=p_category).order_by('-modified_time')
    # return render(request, 'blog/index.html', {'post_list': post_list})
    return redirect('/blog/index?p_category=%s' % (p_category))


# def p_tags(request):
#     p_tag = request.GET.get('tag')
#     post_list = Post.objects.filter(tag__name=p_tag).order_by('-create_time')
#     return render(request, 'blog/index.html', {'post_list': post_list})


# 使用跳转到首页视图的方式添加分页功能
def p_tags(request):
    p_tag = request.GET.get('tag',None)
    # post_list = Post.objects.filter(tag__name=p_tag).order_by('-create_time')
    return redirect('/blog/index?p_tag=%s' % (p_tag))


# 未知如何获取request，废弃
# # 使用ListView改写
# class TagList(ListView):
#     context_object_name = "post_list"
#     model = Post
#     template_name = 'blog/index.html'
#
#     def get_queryset(self):
#         p_tag = self.kwargs.get('tag')
#         print("====================")
#         print(p_tag)
#         return super(TagList,self).get_queryset().filter(tag__name = p_tag).order_by('-create_time')



def search(request):
    s_word = request.POST.get('search')

    error_msg = ''

    if not s_word:
        error_msg = '请输入关键字'
        return render(request, 'blog/index.html',{'error_msg':error_msg})
    post_list = Post.objects.filter(Q(title__icontains=s_word) | Q(content__icontains=s_word))

    PAGE_NUM = 1
    page_count = ceil(len(post_list) / PAGE_NUM)
    page = request.GET.get('page', 1)
    # pages = ceil(Post.objects.count())
    search_paginator = Paginator(post_list, PAGE_NUM)
    post_list = search_paginator.page(page)
    return render(request, 'blog/index.html',
                  {"post_list": post_list, "page_num": range(page_count), "search_paginator": search_paginator})


# 联系板块
def relation(request):
    ralation_msg = "yes"
    return render(request, 'blog/relation.html',{"ralation_msg":ralation_msg})

templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
    <div align="center">
        {% for post in post_list %}
            <article class="post post-4" style="height: 300px;">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="/blog/detail/?post={{ post.id }}">{{ post.title }}</a>
                    </h1>
                    <div class="entry-meta">
                        <span class="post-category"><a href="#">{{ post.category }}</a></span>
                        <span class="post-date"><a href="#"><time class="entry-date"
                                                                  datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                        <span class="post-author"><a href="#">{{ post.user }}</a></span>
                        <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                        <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{{ post.excerpt }}...</p>
                    <div class="read-more cl-effect-14">
                        <a href="/blog/detail/?post={{ post.id }}" class="more-link">继续阅读 <span
                                class="meta-nav">→</span></a>
                    </div>
                </div>
            </article>
        {% endfor %}
        <div class="pagination">
            {% if paginator %}

                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% for page_n in page_num %}
                            <li><a href="/blog/index/?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                        {% endfor %}
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            {% endif %}
        </div>

    </div>

{% endblock %}

templates/blog/page.html
{% extends 'base.html' %}

{% block content %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2017-12-03T23:15:57+00:00">2017年12月03日</time></a></span>
                <span class="post-author"><a href="#">{{ post.user }}</a></span>
                <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">

            <p>
                {{ post.content | safe }}
            </P>
        </div>
{#        显示文章标签，废弃#}
        <div class="widget-tag-cloud">
            <ul>
                标签：
                {% for tag in post.tag.all %}
                    <li><a href="#"># {{ tag }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </article>

{% endblock %}
{% block post_comment %}
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="/blog/detail/?post={{ post.id }}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="#">名字：</label>
                    {{ comment_form.name }}
                    {#                    {{ comment_form.name.errors }}#}
                </div>
                <div class="col-md-4">
                    <label for="#">邮箱：</label>
                    {{ comment_form.email }}
                    {#                    {{ comment_form.email.errors }}#}
                </div>
                <div class="col-md-4">
                    <label for="#">网址：</label>
                    {{ comment_form.url }}
                    {#                    {{ comment_form.url.errors }}#}
                </div>
                <div class="col-md-12">
                    <label for="#">评论：</label>
                    {{ comment_form.text }}
                    {#                    {{ comment_form.text.errors }}#}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>

{% endblock %}

templates/blog/relation.html
{% extends 'base.html' %}


{#meta#}
{% block meta %}

{% endblock %}


{#title#}
{% block title %}
    <title>联系作者 - 博客笔记</title>

{% endblock %}


{#css#}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">


{% endblock %}


{% block boke %}
    {#        联系显示#}
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="blog/index.html"><b>博客笔记需要您的宝贵意见</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    {#                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
                    {#                            <ul class="nav navbar-nav navbar-right">#}
                    {#                                                    <li class="cl-effect-11"><a href="{% url 'login' %}" data-hover="忘记密码">忘记密码</a></li>#}
                    {#                                <li class="cl-effect-11"><a href="{% url 'login' %}" data-hover="主页">主页</a></li>#}

                    {#                            <li class="cl-effect-11"><a href="{% url 'user:register' %}" data-hover="注册新账号">注册新账号</a></li>#}
                    {#                            </ul>#}
                    {#                        </div><!-- /.navbar-collapse -->#}
                </nav>
                {#                <div id="header-search-box">#}
                {#                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>#}
                {#                    <div id="search-form" class="search-form">#}
                {#                        <form role="search" method="post" id="searchform" action="/blog/search/">#}
                {#                            {% csrf_token %}#}
                {#                            <input type="search" name="search" placeholder="搜索" required>#}
                {#          if                  <button type="submit"><span class="ion-ios-search-strong"></span></button>#}
                {#                        </form>#}
                {#                    </div>#}
                {#                </div>#}
            </div><!-- col-md-8 -->
        </div>
    </header>
        <div class="flex-center">
        <div class="container">
            <div>
                <h1 class="logo"><a href="#">热烈欢迎提交意见 </a></h1>
            </div>
        </div>


    </div>
    <div class="flex-center">
        <div>
            <h1>联系方式： <span class="glyphicon glyphicon-envelope"
                            aria-hidden="true"></span><span>luzulin33@163.com</span></h1>

        </div>
    </div>
{% endblock %}


{#js_one#}
{% block js_one %}

{% endblock %}


{#js_end#}
{% block js_end %}
{% endblock %}


{#content#}
{#{% block content %}#}
{##}
{##}
{#{% endblock %}#}
