blog/urls.py
#!/usr/local/python3/bin/python3
from django.conf.urls import url
from blog import views
from .feeds import PostRssFeed


urlpatterns = [
    url(r'index/', views.index, name='index'),
    url(r'detail/', views.detail, name='detail'),
    url(r'p_time/(?P<year>[0-9]{4})/(?P<month>[1-9]|1[0-2])/(?P<day>[0-9]|1[0-9]|2[0-9]|3[0-1])/$', views.p_time, name='p_time'),
    url(r'p_category/', views.p_category, name='p_category'),
    url(r'p_tags/', views.p_tags, name='p_tags'),
    url(r'rss/', PostRssFeed(), name='rss'),
    url(r'search/', views.search, name='search'),
    url(r'relation/', views.relation, name='relation'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    # url(r'^rss/', include('rss.urls', namespace='rss'))
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^user/', include('django.contrib.auth.urls'))
]

user/urls.py
from django.conf.urls import url, static
# from django.conf import settings
# from myblog import settings

from user import views

urlpatterns = [
    url(r'register/$', views.register, name='register'),
    url(r'personInfo/$', views.personInfo, name='personInfo'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    name = models.CharField(max_length = 40, blank=True)
    headshot = models.ImageField(upload_to = '%Y/%m/%d',default='default.jpg',blank=True,null=True,verbose_name='头像')
    signature = models.CharField(max_length=128, default='None')


    class Meta(AbstractUser.Meta):
        pass

user/forms.py
from django.contrib.auth.forms import UserCreationForm


from .models import User

class UserForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username','email', 'headshot', 'signature']

user/views.py
from django.shortcuts import render ,redirect,reverse
from django.http import HttpResponse


from .forms import UserForm
from .models import User
# Create your views here.
def register(request):
    error_msg = ''
    if request.method == 'POST':
        userForm = UserForm(request.POST, request.FILES)
        if userForm.is_valid():
            userForm.save()
            succee_register = "yes"
            return render(request,'user/register_done.html',{"succee_register":succee_register})

        else:
            error_msg = '信息验证有误'


    if request.method == 'GET':
        userForm = UserForm()
    return render(request, 'user/register.html', {'userForm':userForm,"error_msg":error_msg})


def personInfo(request):
    # user = User.objects.get(username = request.user.username)

    # userInfoForm = UserForm(user)
    userInfoForm = UserForm()
    # print(type(request.user.username))
    return render(request, 'user/personInfo.html',{"userInfoForm":userInfoForm})

templates/user/personInfo.html
{% extends 'base.html' %}


{#meta#}
{% block meta %}
    {{ block.super }}

{% endblock %}


{#title#}
{% block title %}
    <title>注册 - 博客笔记</title>
{% endblock %}


{#css#}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="flex-center">
        <div class="container">
            <div class="flex-center">
                <div class="unit-1-2 unit-1-on-mobile">


                    {% if error_msg %}
                        {{ error_msg }}
                    {% endif %}
                    <form class="form" action="#" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for error in userInfoForm.errors %}
                            {{ error }}
                        {% endfor %}
                        {% for field in userInfoForm %}
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                            {{ field.help_text | safe }}
                            {#                        {% if field.help_text %}#}
                            {#                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
                            {#                        {% endif %}#}
                        {% endfor %}
                        <h1><a href="{% url 'password_change' %}">修改密码</a></h1>
                        <button type="submit" class="btn btn-primary btn-block">提交信息</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/register.html
{#{% extends 'base.html' %}#}
{#{% block userRegister %}#}
{#<form action="/user/register" method="post" enctype="multipart/form-data">#}
{#    {% csrf_token %}#}
{#    {% for field in userForm %}#}
{#    {{ field.label_tag }}#}
{#    {{ field }}#}
{#        {{ field.errors}}#}
{##}
{#    {% endfor %}#}
{#</form>#}
{#    <form class="form" action="/user/register" method="post" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        {% for field in userForm %}#}
{#            {{ field.label_tag }}#}
{#            {{ field }}#}
{#            {{ field.errors }}#}
{#            {% if field.help_text %}#}
{#                <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
{#            {% endif %}#}
{#        {% endfor %}#}
{#        <button type="submit" class="btn btn-primary btn-block">注册</button>#}
{#        <input type="hidden" name="next" value="{{ next }}"/>#}
{#    </form>#}
{#    #}
{#    #}
{#    #}
{#    #}
{##}
{#{% endblock %}#}
{##}
{##}
{#<!DOCTYPE html>#}
{#<html lang="zh-cn">#}
{#<head>#}
{#    <meta charset="utf-8">#}
{#    <meta http-equiv="x-ua-compatible" content="ie=edge">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">#}
{#    <title>注册</title>#}
{#    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">#}
{#    <style>#}
{#        .errorlist {#}
{#            color: red;#}
{#        }#}
{#    </style>#}
{#</head>#}
{#<body>#}
{#<div class="flex-center">#}
{#    <div class="container">#}
{#        <div class="flex-center">#}
{#            <div class="unit-1-2 unit-1-on-mobile">#}
{#                <h1><a href="{% url 'blog:index' %}">注冊讀書博客</a></h1>#}
{#                <h3>注册</h3>#}
{#            {%  if error_msg  %}#}
{#            {{ error_msg }}#}
{#            {% endif %}#}
{#                <form class="form" action="{% url 'user:register' %}" method="post" enctype="multipart/form-data" >#}
{#                    {% csrf_token %}#}
{#                {% for error in userForm.errors %}#}
{#                    {{ error }}#}
{#                {% endfor %}#}
{#                    {% for field in userForm %}#}
{#                        {{ field.label_tag }}#}
{#                        {{ field }}#}
{#                        {{ field.errors }}#}
{#                        {{ field.help_text | safe }}#}
{#                        {% if field.help_text %}#}
{#                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
{#                        {% endif %}#}
{#                    {% endfor %}#}
{#                    <button type="submit" class="btn btn-primary btn-block">注册</button>#}
{#                    <input type="hidden" name="next" value="{{ next }}"/>#}
{#                </form>#}
{#                <div class="flex-center top-gap text-small">#}
{#                    <a href="#">已有账号登录</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#</body>#}
{#</html>#}
{##}


{% extends 'base.html' %}


{#meta#}
{% block meta %}
    {{ block.super }}

{% endblock %}


{#title#}
{% block title %}
    <title>注册 - 博客笔记</title>
{% endblock %}


{#css#}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="flex-center">
        <div class="container">
            <div class="flex-center">
                <div class="unit-1-2 unit-1-on-mobile">
                    <h1><a href="{% url 'blog:index' %}">注冊讀書博客</a></h1>
                    {% if error_msg %}
                        {{ error_msg }}
                    {% endif %}
                    <form class="form" action="{% url 'user:register' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for error in userForm.errors %}
                            {{ error }}
                        {% endfor %}
                        {% for field in userForm %}
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                            {{ field.help_text | safe }}
                            {#                        {% if field.help_text %}#}
                            {#                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
                            {#                        {% endif %}#}
                        {% endfor %}
                        <button type="submit" class="btn btn-primary btn-block">注册</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                    <div class="flex-center top-gap text-small">
                        <a href="#">已有账号登录</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}



templates/user/register_done.html


{% extends 'base.html' %}


{#meta#}
{% block meta %}

{% endblock %}


{#title#}
{% block title %}
    <title>注册成功 - 博客笔记</title>

{% endblock %}


{#css#}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">


{% endblock %}


{#content#}
{% block content %}
    <div class="flex-center">
        <div class="container">
            <div>
                <h1 class="logo"><a href="{% url 'blog:index' %}">成功注册</a></h1>
            </div>
        </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            {#                                                    <li class="cl-effect-11"><a href="{% url 'login' %}" data-hover="忘记密码">忘记密码</a></li>#}
            <li class="cl-effect-11"><a href="{% url 'login' %}" data-hover="">点击登陆</a></li>

            {#                            <li class="cl-effect-11"><a href="{% url 'user:register' %}" data-hover="注册新账号">注册新账号</a></li>#}
        </ul>
    </div><!-- /.navbar-collapse -->
{% endblock %}


{#js_one#}
{% block js_one %}

{% endblock %}


{#js_end#}
{% block js_end %}

{% endblock %}
